(define-module (myabinit)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix build-system gnu)
 ; #:use-module (guix build utils)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:use-module (gnu packages algebra)
  #:use-module (gnu packages autotools)
  ;#:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages maths)
  #:use-module (gnu packages m4)
  #:use-module (gnu packages mpi)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-xyz)
  #:use-module (myquantum-espresso)
)

(define-public libxc
  (package
    (name "libxc")
    (version "5.1.5")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
         (url "https://gitlab.com/libxc/libxc.git")
         (commit version)))
       (file-name (git-file-name name version))
       (sha256
        (base32
         "0cy3x2zn1bldc5i0rzislfbc8h4nqgds445jkfqjv0d1shvdy0zn"))))
    (build-system gnu-build-system)
    (native-inputs
     `(("automake" ,automake)
       ("autoconf" ,autoconf)
       ("bash" ,bash)
       ("gfortran" ,gfortran)
       ("libtool" ,libtool)
       ("perl" ,perl)
       ("pkg-config" ,pkg-config)))
    (arguments
     `(#:configure-flags (list "--enable-shared")))
    (home-page "")
    (synopsis "")
    (description "")
    (license license:mpl2.0)))


(define-public myabinit
  (package
  (name "myabinit")
  (version "9.10.1")
  (source (origin
            (method url-fetch)
	    (uri (string-append "https://github.com/abinit/abinit/archive/refs/tags/" version ".tar.gz"))
            (sha256
             (base32
              "16vmiwlq9l7qxxw7f36sc6pvrn1724jywd83pra71f73nyb4sr0b"))))
  (build-system gnu-build-system)
  (arguments
   `(#:phases
      (modify-phases %standard-phases
        (delete 'configure)
        (add-after `unpack `patch-interpreters
           (lambda* (#:key inputs #:allow-other-keys)
              ;;;;; TODO -> finish this patching (find a way to have a clean recursive find-files ?)
              (substitute* (find-files "." "\\.py$")
                (("/usr/bin/env python3")
                (string-append (assoc-ref inputs "python") "/bin/python3"))
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "." "config\\$")
                (("/bin/sh")
                (which "sh")))
              (substitute* (find-files "." "\\.pl$")
                (("/bin/env perl")
                (string-append (assoc-ref inputs "perl") "/bin/perl")))
              (substitute* (find-files "./config")
                (("/bin/sh")
                (which "sh"))
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3"))
                (("/bin/cp")
                (which "cp")))
              (substitute* (find-files "./bindings")
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./bindings")
                (("/bin/sh")
                (which "sh")))
              (substitute* (find-files "." "\\.sh$")
                (("/bin/sh")
                (which "sh")))
              (substitute* (find-files "./developers")
                (("/bin/csh")
                (which "sh")))
              (substitute* (find-files "./scripts" "\\.py$")
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./scripts/post_processing" "\\.py$")
                (("/usr/bin/python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./scripts/pre_processing" "\\.py$")
                (("/usr/bin/python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./scripts/configure/abinit_config" "\\.py$")
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./scripts/configure/abinit_config" "abinit-textconfig")
                (("/usr/bin/python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./scripts/configure/abinit_config" "\\.py$")
                (("/usr/bin/python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./tests" "\\.py$")
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./tests/config/scripts")
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./doc/config/scripts")
                (("/usr/bin/env python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* (find-files "./doc/tutorial/paral_moldyn_assets" "\\.py$")
                (("/usr/bin/env  python")
                (string-append (assoc-ref inputs "python") "/bin/python3")))
              (substitute* "configure.ac"
                (("/bin/sh")
                (which "sh")))
              ))
        (replace 'install
             (lambda* (#:key outputs inputs #:allow-other-keys)
                (let* ((out (assoc-ref outputs "out"))
                    (bindir (string-append out "/bin"))
                    (incdir (string-append out "/include"))
                    (libdir (string-append out "/lib")))
                    (for-each (lambda (f) (install-file f libdir))
                             (find-files "./src/" "\\.a"))
                    (for-each (lambda (f) (install-file f incdir))
                             (find-files "./src/" "\\.hh"))
                    (install-file "./src/abinit" bindir))))
        (replace `build
          (lambda* (#:key outputs inputs version #:allow-other-keys)
            (mkdir-p "./tmp")
            (chdir "./tmp")
            (invoke "../configure")
          )
        )
      )
      #:tests? #f))
  (inputs
     `(("gcc" ,gcc)
       ("gzip" ,gzip)
       ("gfortran", gfortran)
       ("python", python)
       ("perl" ,perl)
       ("openmpi" ,openmpi)
       ("hdf5" ,hdf5)
       ("fftw" ,fftw)
       ("libxc", libxc)
       ("python-netcdf4",python-netcdf4) ; verify this
       ("openblas" ,openblas)
       ("m4" ,m4)
       ("autoconf" ,autoconf)
       ("automake" ,automake)
       ("libtool" ,libtool)
       ("wannier90" ,wannier90) ; -> copied the one from QE ; can we use it instead ? 
       ))
  (native-search-paths
    (lambda* (#:key outputs inputs version #:allow-other-keys)
      (list (assoc-ref inputs "bash"))
    )
  )
  (native-inputs
    `(("bc" ,bc)))
  (synopsis "ABINIT is a software suite to calculate the optical, mechanical, vibrational, and other observable properties of materials.")
  (description "Starting from the quantum equations of density functional theory, you can build up to advanced applications with perturbation theories based on DFT, and many-body Green's functions (GW and DMFT). ABINIT can calculate molecules, nanostructures and solids with any chemical composition, and comes with several complete and robust tables of atomic potentials.")
  (home-page "https://www.abinit.org/")
  (license license:gpl2+)))
  myabinit
